use_frameworks!
platform :ios, '12.1'

target 'ProvaPod_Tests' do

  pod 'ProvaPod', :path => '../'
  pod 'Bluejay', '~> 0.8'
  pod 'XCGLogger', '~> 6.1.0'
  pod 'PromiseKit', '~> 6.8.3'
  pod 'ZIPFoundation', '~> 0.9.9'
  
end
