use_frameworks!
platform :ios, '12.1'

target 'MyBike_BLE_Tests' do

  pod 'MyBike_BLE', :path => '../'
  pod 'Bluejay', '~> 0.8'
  pod 'XCGLogger', '~> 6.1.0'
  pod 'PromiseKit', '~> 6.8.3'
  pod 'ZIPFoundation', '~> 0.9.9'
#  pod 'Quick', '~> 2.2.0'
#  pod 'Nimble', '~> 8.0.7'

end
